# render.yaml - Configuration for Render deployment
services:
  # Backend API service
  - type: web
    name: recipe-ai-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false  # This will be a secret you'll need to set manually in Render
      - key: postgresql://recipeai_qf7f_user:hLXJot8JVTwfhuWleYZ5qDT62vGBdjjG@dpg-d06iir2li9vc73edukr0-a.oregon-postgres.render.com/recipeai_qf7f
        fromDatabase:
          name: recipeAI
          property: connectionString

databases:
  
  - name: recipe-ai-db
    plan: free
    databaseName: recipe_ai
    ipAllowList:
      - source: 0.0.0.0/0  # Allow connections from anywhere (you might want to restrict this in production)